return {
    light = {
        low = function(colors)
            return {
                bg0 = colors.light2,
                bg1 = colors.light3,
                bg2 = colors.light4,
                bg3 = colors.light5,
                fg0 = colors.dark2,
                fg1 = colors.dark3,
                fg2 = colors.dark4,
                fg3 = colors.dark5,
                red0 = colors.red2,
                red1 = colors.red3,
                orange0 = colors.orange2,
                orange1 = colors.orange3,
                yellow0 = colors.yellow2,
                yellow1 = colors.yellow3,
                green0 = colors.green2,
                green1 = colors.green3,
                teal0 = colors.teal2,
                teal1 = colors.teal3,
                aqua0 = colors.aqua2,
                aqua1 = colors.aqua3,
                blue0 = colors.blue2,
                blue1 = colors.blue3,
                purple0 = colors.purple2,
                purple1 = colors.purple3,
                brown0 = colors.brown2,
                brown1 = colors.brown3,
            }
        end,
        medium = function(colors)
            return {
                bg0 = colors.light1,
                bg1 = colors.light2,
                bg2 = colors.light5,
                bg3 = colors.light6,
                fg0 = colors.dark1,
                fg1 = colors.dark2,
                fg2 = colors.dark5,
                fg3 = colors.dark6,
                red0 = colors.red3,
                red1 = colors.red4,
                orange0 = colors.orange3,
                orange1 = colors.orange4,
                yellow0 = colors.yellow3,
                yellow1 = colors.yellow4,
                green0 = colors.green3,
                green1 = colors.green4,
                teal0 = colors.teal3,
                teal1 = colors.teal4,
                aqua0 = colors.aqua3,
                aqua1 = colors.aqua4,
                blue0 = colors.blue3,
                blue1 = colors.blue4,
                purple0 = colors.purple3,
                purple1 = colors.purple4,
                brown0 = colors.brown3,
                brown1 = colors.brown4,
            }
        end,
        high = function(colors)
            return {
                bg0 = colors.light0,
                bg1 = colors.light1,
                bg2 = colors.light6,
                bg3 = colors.light7,
                fg0 = colors.dark0,
                fg1 = colors.dark1,
                fg2 = colors.dark6,
                fg3 = colors.dark7,
                red0 = colors.red4,
                red1 = colors.red5,
                orange0 = colors.orange4,
                orange1 = colors.orange5,
                yellow0 = colors.yellow4,
                yellow1 = colors.yellow5,
                green0 = colors.green4,
                green1 = colors.green5,
                teal0 = colors.teal4,
                teal1 = colors.teal5,
                aqua0 = colors.aqua4,
                aqua1 = colors.aqua5,
                blue0 = colors.blue4,
                blue1 = colors.blue5,
                purple0 = colors.purple4,
                purple1 = colors.purple5,
                brown0 = colors.brown4,
                brown1 = colors.brown5,
            }
        end,
    },
    dark = {
        low = function(colors)
            return {
                bg0 = colors.dark2,
                bg1 = colors.dark3,
                bg2 = colors.dark4,
                bg3 = colors.dark5,
                fg0 = colors.light2,
                fg1 = colors.light3,
                fg2 = colors.light4,
                fg3 = colors.light5,
                red0 = colors.red3,
                red1 = colors.red2,
                orange0 = colors.orange3,
                orange1 = colors.orange2,
                yellow0 = colors.yellow3,
                yellow1 = colors.yellow2,
                green0 = colors.green3,
                green1 = colors.green2,
                teal0 = colors.teal3,
                teal1 = colors.teal2,
                aqua0 = colors.aqua3,
                aqua1 = colors.aqua2,
                blue0 = colors.blue3,
                blue1 = colors.blue2,
                purple0 = colors.purple3,
                purple1 = colors.purple2,
                brown0 = colors.brown3,
                brown1 = colors.brown2,
            }
        end,
        medium = function(colors)
            return {
                bg0 = colors.dark1,
                bg1 = colors.dark2,
                bg2 = colors.dark5,
                bg3 = colors.dark6,
                fg0 = colors.light1,
                fg1 = colors.light2,
                fg2 = colors.light5,
                fg3 = colors.light6,
                red0 = colors.red2,
                red1 = colors.red1,
                orange0 = colors.orange2,
                orange1 = colors.orange1,
                yellow0 = colors.yellow2,
                yellow1 = colors.yellow1,
                green0 = colors.green2,
                green1 = colors.green1,
                teal0 = colors.teal2,
                teal1 = colors.teal1,
                aqua0 = colors.aqua2,
                aqua1 = colors.aqua1,
                blue0 = colors.blue2,
                blue1 = colors.blue1,
                purple0 = colors.purple2,
                purple1 = colors.purple1,
                brown0 = colors.brown2,
                brown1 = colors.brown1,
            }
        end,
        high = function(colors)
            return {
                bg0 = colors.dark0,
                bg1 = colors.dark1,
                bg2 = colors.dark6,
                bg3 = colors.dark7,
                fg0 = colors.light0,
                fg1 = colors.light1,
                fg2 = colors.light6,
                fg3 = colors.light7,
                red0 = colors.red1,
                red1 = colors.red0,
                orange0 = colors.orange1,
                orange1 = colors.orange0,
                yellow0 = colors.yellow1,
                yellow1 = colors.yellow0,
                green0 = colors.green1,
                green1 = colors.green0,
                teal0 = colors.teal1,
                teal1 = colors.teal0,
                aqua0 = colors.aqua1,
                aqua1 = colors.aqua0,
                blue0 = colors.blue1,
                blue1 = colors.blue0,
                purple0 = colors.purple1,
                purple1 = colors.purple0,
                brown0 = colors.brown1,
                brown1 = colors.brown0,
            }
        end,
    },
}
