return {
    light = {
        low = function(colors)
            return {
                bg0 = colors.leaf_light_2,
                bg1 = colors.leaf_light_3,
                bg2 = colors.leaf_light_4,
                bg3 = colors.leaf_light_5,
                fg0 = colors.leaf_dark_3,
                fg1 = colors.leaf_dark_2,
                fg2 = colors.leaf_dark_1,
                fg3 = colors.leaf_dark_0,
                red0 = colors.leaf_red_3,
                red1 = colors.leaf_red_2,
                orange0 = colors.leaf_orange_3,
                orange1 = colors.leaf_orange_2,
                yellow0 = colors.leaf_yellow_3,
                yellow1 = colors.leaf_yellow_2,
                green0 = colors.leaf_green_3,
                green1 = colors.leaf_green_2,
                teal0 = colors.leaf_teal_3,
                teal1 = colors.leaf_teal_2,
                aqua0 = colors.leaf_aqua_3,
                aqua1 = colors.leaf_aqua_2,
                blue0 = colors.leaf_blue_3,
                blue1 = colors.leaf_blue_2,
                purple0 = colors.leaf_purple_3,
                purple1 = colors.leaf_purple_2,
                brown0 = colors.leaf_brown_3,
                brown1 = colors.leaf_brown_2,
            }
        end,
        medium = function(colors)
            return {
                bg0 = colors.leaf_light_1,
                bg1 = colors.leaf_light_2,
                bg2 = colors.leaf_light_3,
                bg3 = colors.leaf_light_6,
                fg0 = colors.leaf_dark_3,
                fg1 = colors.leaf_dark_2,
                fg2 = colors.leaf_dark_1,
                fg3 = colors.leaf_dark_0,
                red0 = colors.leaf_red_4,
                red1 = colors.leaf_red_3,
                orange0 = colors.leaf_orange_4,
                orange1 = colors.leaf_orange_3,
                yellow0 = colors.leaf_yellow_4,
                yellow1 = colors.leaf_yellow_3,
                green0 = colors.leaf_green_4,
                green1 = colors.leaf_green_3,
                teal0 = colors.leaf_teal_4,
                teal1 = colors.leaf_teal_3,
                aqua0 = colors.leaf_aqua_4,
                aqua1 = colors.leaf_aqua_3,
                blue0 = colors.leaf_blue_4,
                blue1 = colors.leaf_blue_3,
                purple0 = colors.leaf_purple_4,
                purple1 = colors.leaf_purple_3,
                brown0 = colors.leaf_brown_4,
                brown1 = colors.leaf_brown_3,
            }
        end,
        high = function(colors)
            return {
                bg0 = colors.leaf_light_0,
                bg1 = colors.leaf_light_1,
                bg2 = colors.leaf_light_2,
                bg3 = colors.leaf_light_7,
                fg0 = colors.leaf_dark_3,
                fg1 = colors.leaf_dark_2,
                fg2 = colors.leaf_dark_1,
                fg3 = colors.leaf_dark_0,
                red0 = colors.leaf_red_5,
                red1 = colors.leaf_red_4,
                orange0 = colors.leaf_orange_5,
                orange1 = colors.leaf_orange_4,
                yellow0 = colors.leaf_yellow_5,
                yellow1 = colors.leaf_yellow_4,
                green0 = colors.leaf_green_5,
                green1 = colors.leaf_green_4,
                teal0 = colors.leaf_teal_5,
                teal1 = colors.leaf_teal_4,
                aqua0 = colors.leaf_aqua_5,
                aqua1 = colors.leaf_aqua_4,
                blue0 = colors.leaf_blue_5,
                blue1 = colors.leaf_blue_4,
                purple0 = colors.leaf_purple_5,
                purple1 = colors.leaf_purple_4,
                brown0 = colors.leaf_brown_5,
                brown1 = colors.leaf_brown_4,
            }
        end,
    },
    dark = {
        low = function(colors)
            return {
                bg0 = colors.leaf_dark_2,
                bg1 = colors.leaf_dark_3,
                bg2 = colors.leaf_dark_4,
                bg3 = colors.leaf_dark_5,
                fg0 = colors.leaf_light_3,
                fg1 = colors.leaf_light_2,
                fg2 = colors.leaf_light_1,
                fg3 = colors.leaf_light_0,
                red0 = colors.leaf_red_2,
                red1 = colors.leaf_red_3,
                orange0 = colors.leaf_orange_2,
                orange1 = colors.leaf_orange_3,
                yellow0 = colors.leaf_yellow_2,
                yellow1 = colors.leaf_yellow_3,
                green0 = colors.leaf_green_2,
                green1 = colors.leaf_green_3,
                teal0 = colors.leaf_teal_2,
                teal1 = colors.leaf_teal_3,
                aqua0 = colors.leaf_aqua_2,
                aqua1 = colors.leaf_aqua_3,
                blue0 = colors.leaf_blue_2,
                blue1 = colors.leaf_blue_3,
                purple0 = colors.leaf_purple_2,
                purple1 = colors.leaf_purple_3,
                brown0 = colors.leaf_brown_2,
                brown1 = colors.leaf_brown_3,
            }
        end,
        medium = function(colors)
            return {
                bg0 = colors.leaf_dark_1,
                bg1 = colors.leaf_dark_2,
                bg2 = colors.leaf_dark_3,
                bg3 = colors.leaf_dark_6,
                fg0 = colors.leaf_light_3,
                fg1 = colors.leaf_light_2,
                fg2 = colors.leaf_light_1,
                fg3 = colors.leaf_light_0,
                red0 = colors.leaf_red_1,
                red1 = colors.leaf_red_2,
                orange0 = colors.leaf_orange_1,
                orange1 = colors.leaf_orange_2,
                yellow0 = colors.leaf_yellow_1,
                yellow1 = colors.leaf_yellow_2,
                green0 = colors.leaf_green_1,
                green1 = colors.leaf_green_2,
                teal0 = colors.leaf_teal_1,
                teal1 = colors.leaf_teal_2,
                aqua0 = colors.leaf_aqua_1,
                aqua1 = colors.leaf_aqua_2,
                blue0 = colors.leaf_blue_1,
                blue1 = colors.leaf_blue_2,
                purple0 = colors.leaf_purple_1,
                purple1 = colors.leaf_purple_2,
                brown0 = colors.leaf_brown_1,
                brown1 = colors.leaf_brown_2,
            }
        end,
        high = function(colors)
            return {
                bg0 = colors.leaf_dark_0,
                bg1 = colors.leaf_dark_1,
                bg2 = colors.leaf_dark_2,
                bg3 = colors.leaf_dark_7,
                fg0 = colors.leaf_light_3,
                fg1 = colors.leaf_light_2,
                fg2 = colors.leaf_light_1,
                fg3 = colors.leaf_light_0,
                red0 = colors.leaf_red_0,
                red1 = colors.leaf_red_1,
                orange0 = colors.leaf_orange_0,
                orange1 = colors.leaf_orange_1,
                yellow0 = colors.leaf_yellow_0,
                yellow1 = colors.leaf_yellow_1,
                green0 = colors.leaf_green_0,
                green1 = colors.leaf_green_1,
                teal0 = colors.leaf_teal_0,
                teal1 = colors.leaf_teal_1,
                aqua0 = colors.leaf_aqua_0,
                aqua1 = colors.leaf_aqua_1,
                blue0 = colors.leaf_blue_0,
                blue1 = colors.leaf_blue_1,
                purple0 = colors.leaf_purple_0,
                purple1 = colors.leaf_purple_1,
                brown0 = colors.leaf_brown_0,
                brown1 = colors.leaf_brown_1,
            }
        end,
    },
}
